### ISSUE TITLE
suggest get fileExtension from download url.

### ISSUE THREAD

**Issue by badboy-tian** [renefloor/flutter_cache_manager#92] opened 2019-05-30 03:11 UTC
I have a mp3 url, like http://xxx.com/dddd.mp3
and the context-type is audio/mpeg.
and then  i found the cache path is xxx.mpeg,
In ios, it can not play use xxx.mpeg.

so, i change the code:
```
 var fileExtension = "";
    if (url.isNotEmpty && url.lastIndexOf(".") != -1) {
      fileExtension = url.substring(url.lastIndexOf("."), url.length);
    } else {
      if (response.hasHeader("content-type")) {
        var type = response.header("content-type").split("/");
        if (type.length == 2) {
          fileExtension = ".${type[1]}";
        }
      }
    }
```
And the cache file is xxx.mp3 now,  and can play normal.

**Comment by renefloor** [comment] 2019-07-15 05:52
Duplicate of #74

**Closed** 2019-07-15 05:52 UTC
